[package]
name = "gossip"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-client = {workspace = true}
solana-gossip = {workspace = true}
solana-sdk = {workspace = true}
solana-streamer = {workspace = true}